### ISSUE TITLE
Improve mailmap

### ISSUE THREAD

**Issue by rgaiacs** [swcarpentry/bc#576]
When run `make contribs` there a few contributors that should be at `.mailmap`.
- [x] @AnneTheAgile
- [x] @BillMills (addressed at #577)
- [x] Brenna (addressed at #577)
- [x] @dbarneche (addressed at #577)
- [x] @dtrap (addressed at #577)
- [x] Erik Bray (addressed at #577)
- [x] MollyGibson (addressed at #577)
- [x] r-gaia-cs (addressed at #577)
