### ISSUE TITLE
[meta] Instructors with different spelling at bootcamps_saved.yml

### ISSUE THREAD

**Issue by r-gaia-cs** [swcarpentry/bc#596]
The name of some instructors has two different spellings at `bootcamps_saved.yml` and this is a problem for #578. One solution is fix instructors name at bootcamps index page and update `bootcamps_saved.yml` and another one, [suggested by](https://github.com/swcarpentry/2014-04-14-pycon-ngs/issues/2#issuecomment-48850135) @wking is use .mailmap-style name-canonicalization.

Comments are welcome.

### List of names with problems

- [ ] "C. Titus Brown" vs "Titus Brown" (suggested solution at swcarpentry/2014-04-14-pycon-ngs#2)
- [x] "Gabriel Devenyi" vs "Gabriel A. Devenyi" (suggested solution at gdevenyi/2014-06-04-cornell#2)
- [ ] "Stephen J. Eglen" vs "Stephen Eglen"
- [ ] "Steven Haddock" vs "Steve Haddock"
- [ ] "Joshua Herr" vs "Joshua R. Herr"
- [ ] "Adina Howe" vs "Adina Chuang Howe"
- [ ] "and Suzanne Kiihne" vs "Suzanne Kiihne"
- [ ] "W. Trevor King" vs "Trevor King"
- [ ] "Michael Selik" vs "Mike Selik"
- [ ] "William Trimble" vs "Will Trimble"
